Daniel sanabria 3126898866 tarea 7
sergio-ceballos-intelex/tareas-modulo-3-grupo-8 pull request #71
Opened 2024-06-03 17:29 UTC by Pininita

Entrega de tarea 7 completa y con comentarios de lo que se aprendió nuevo y alguna otra forma en la que logre obtener el resultado

2024-06-04 15:43 UTC, sergio-ceballos-intelex commented on daniel-sanabria-3126898866/tarea-7/main7.js
> +olderStudents = olderStudents.concat(studentsTwenty) //.concat para concatenar
esto no es necesario, si te fijas en realidad no aporta nada al codigo solo lo hace mas dificil de entender

2024-06-04 15:44 UTC, sergio-ceballos-intelex commented on daniel-sanabria-3126898866/tarea-7/main7.js
> +let highAverage = estudiantes4.filter((student) => {
no entiendo muy bien este codigo, comporbaste que funcionara?

2024-06-04 15:44 UTC, sergio-ceballos-intelex requested changes
solucionar comentarios

2024-06-04 15:56 UTC, Pininita commented on daniel-sanabria-3126898866/tarea-7/main7.js
> +let highAverage = estudiantes4.filter((student) => {
hola, si, ya comprobé y todo funciona

2024-06-04 17:01 UTC, Pininita commented on daniel-sanabria-3126898866/tarea-7/main7.js
> +olderStudents = olderStudents.concat(studentsTwenty) //.concat para concatenar
lo que estoy tratando de conseguir es que me retorne solo el nombre de las personas mayores de 20, le consigo con el .push o con el .concat pero no se de que otra manera lograrlo, subire cambios pero ahora con .push

2024-06-10 21:05 UTC, sergio-ceballos-intelex approved these changes

2024-06-10 21:06 UTC, merged