Erick alvarez 3184596026 tarea6
sergio-ceballos-intelex/tareas-modulo-3-grupo-8 pull request #77
Opened 2024-06-04 00:18 UTC by ErickAlvarez2412

Anexo todos los puntos resueltos en un solo archivo main.js que esta ubicado dentro de la carpeta con el nombre Tarea-6

2024-06-04 16:43 UTC, sergio-ceballos-intelex commented on ERICK-ALVAREZ-3184596026/Tarea-6/main.js
> +    if(title == true){
aqui sobra el == true

2024-06-04 16:43 UTC, sergio-ceballos-intelex requested changes
corregir cambios

2024-06-05 00:53 UTC, ErickAlvarez2412 commented on ERICK-ALVAREZ-3184596026/Tarea-6/main.js
> +    if(title == true){
Ya realice el cambio pertinente.

2024-06-10 21:04 UTC, sergio-ceballos-intelex approved these changes

2024-06-10 21:05 UTC, merged